<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>KUDA55</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>

    <h1>Selamat Datang di KUDA55</h1>

    <p>Website pertama saya.</p>

    <a href="https://wa.me/6281935023482">WhatsApp</a>

</body>
</html>
